nome = str(input('Digite seu nome completo: ')).strip()
nome1 = nome.upper()
nome2 = nome.lower()
nome3 = len(nome) - nome.count(' ')
nome4 = nome.find(' ')
print('Seu nome é {}, em maiúsculo fica {}, em minúsculo, {}'.format(nome, nome1, nome2))
print('Sem considerar os espaços, seu nome tem {} caracteres, e seu primeiro nome, {} caracteres'.format(nome3, nome4))
separa = nome.split()
print(separa)
print('Seu primeiro nome é {} e possui {} caracteres'.format(separa[0], len(separa[0])))